CREATE TABLE public.v2_notas_historial (
    id bigint NOT NULL,
    candidato_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nota text
);

ALTER TABLE public.v2_notas_historial OWNER TO postgres;

ALTER TABLE public.v2_notas_historial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.v2_notas_historial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.v2_notas_historial
    ADD CONSTRAINT v2_notas_historial_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.v2_notas_historial
    ADD CONSTRAINT v2_notas_historial_candidato_id_fkey FOREIGN KEY (candidato_id) REFERENCES public.v2_candidatos(id) ON DELETE CASCADE;

-- Move existing notes to the new history table
INSERT INTO public.v2_notas_historial (candidato_id, nota, created_at)
SELECT id, notas, updated_at FROM public.v2_candidatos WHERE notas IS NOT NULL AND notas != '';

-- Optional: Remove the old 'notas' column from v2_candidatos
-- ALTER TABLE public.v2_candidatos DROP COLUMN notas;
